AVL Tree Implementation: avltree.h File Reference
avltree.h File Reference
Data Structures
struct _avl_node
avl node structure define
struct _avl_ops
callback function table tobe registered by users.
struct _avl_tree
Typedefs
typedef struct _avl_node avl_node_t
avl node structure define
typedef int(* avl_tree_cmp_fp)(const avl_node_t *a, const avl_node_t *b)
prototype of user defined compare function.
typedef struct _avl_ops avl_ops_t
callback function table tobe registered by users.
typedef struct _avl_tree avl_tree_t
Enumerations
enum bool_t { FALSE = 0, TRUE }
Functions
static avl_node_t * avl_find (avl_tree_t *tree, avl_node_t *node)
find a node in avl tree.
void avl_add (avl_tree_t *tree, avl_node_t *node)
add a node to the tree.
void avl_del (avl_tree_t *tree, avl_node_t *node)
When deleting a node, we need to move a new node in the tree to the empty place, there are two candidates: the maximum node of its left subtree, or the minmum node of its right subtree. Here, the former is used.
Detailed Description
Author
jinya.nosp@m.ng.h.nosp@m.ust@g.nosp@m.mail.nosp@m..com
Typedef Documentation
typedef struct _avl_node avl_node_t
avl node structure define
typedef struct _avl_ops avl_ops_t
callback function table tobe registered by users.
typedef int(* avl_tree_cmp_fp)(const avl_node_t *a, const avl_node_t *b)
prototype of user defined compare function.
Returns
0: equal 1: a > b -1: a < b
typedef struct _avl_tree avl_tree_t
Enumeration Type Documentation
enum bool_t
Enumerator
FALSE
TRUE
Function Documentation
void avl_add (avl_tree_t * tree, avl_node_t * node)
add a node to the tree.
Parameters
tree node to be added.
Returns
no
References __avl_add(), _avl_ops::avl_cmp, avl_do_balancing(), avl_is_balanced(), _avl_tree::avl_ops, avl_set_height(), _avl_node::parent, and _avl_tree::root.
void avl_del (avl_tree_t * tree, avl_node_t * node)
When deleting a node, we need to move a new node in the tree to the empty place, there are two candidates: the maximum node of its left subtree, or the minmum node of its right subtree. Here, the former is used.
When deleting a node, we need to move a new node in the tree to the empty place, there are two candidates: the maximum node of its left subtree, or the minmum node of its right subtree. Here, the former is used.
Parameters
tree
node to be deleted.
Returns
none
References avl_do_balancing(), avl_get_max_node(), avl_is_balanced(), avl_set_height(), avl_swap_nodes(), FALSE, _avl_node::left, _avl_node::parent, _avl_node::right, and _avl_tree::root.
static avl_node_t* avl_find (avl_tree_t * tree, avl_node_t * node) static
find a node in avl tree.
Parameters
tree avl tree to be searched.
node
Returns
the found node, or NULL if not found.