AVL Tree Implementation: avltree.c File Reference
avltree.c File Reference
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include "avltree.h"
Functions
static void avl_rotate_rr (avl_node_t **root, avl_node_t *node)
This performs an RR rotation on the tree at the give node. This is required when an unblanced node is right-heavy and the subtree to its right is right-heavy too (for example after a node was inserted into the right subtree's right subtree).
static void avl_rotate_ll (avl_node_t **root, avl_node_t *node)
This performs an LL rotation on the tree at the give node.
static void avl_rotate_lr (avl_node_t **root, avl_node_t *node)
This performs an LR rotation on the tree at the give node. This is required when an unblanced node is left-heavy and the subtree to its left is right-heavy (for example after a node was inserted into the left subtree's right subtree).
static void avl_rotate_rl (avl_node_t **root, avl_node_t *node)
int avl_get_balance (avl_node_t *node)
get balance factor of a tree The balance factor of a tree is the height of left subtree minnus height of right subtree. If balance factor is -1, 0, or 1, then it is a balanced tree. If the balance factor at a node is > 0 then the subtree at that node is left heavy. If it is < 0 then it is right heavy.
bool_t avl_is_balanced (avl_node_t *node)
check if a node is banlanced.
void avl_set_height (avl_node_t *node)
calculate height of all nodes in a tree.
bool_t avl_do_balancing (avl_tree_t *tree, avl_node_t *node)
do balancing operation for a tree required. Balance the un-balanced tree at the given node by RR, LL, RL, LR rotation.
avl_node_t * avl_get_max_node (avl_node_t *node)
get maxmum node in a tree.
avl_node_t * avl_get_min_node (avl_node_t *node)
get mimmum node in a tree.
static avl_node_t * __avl_find (avl_node_t *root, avl_node_t *node, avl_tree_cmp_fp cmp)
genaral binary search tree procedure.
static avl_node_t * avl_find (avl_tree_t *tree, avl_node_t *node)
find a node in avl tree.
static avl_node_t * __avl_add (avl_node_t *root, avl_node_t *root_parent, avl_node_t *node, avl_tree_cmp_fp cmp)
add a new node into tree root.
void avl_add (avl_tree_t *tree, avl_node_t *node)
add a node to the tree.
void avl_swap_nodes (avl_node_t *node1, avl_node_t *node2, avl_tree_t *tree)
swap positions of node1 and node2. Devide this into 3 cases:
void avl_del (avl_tree_t *tree, avl_node_t *node)
delete a node from a tree. When deleting a node, we need to move a new node in the tree to the empty place, there are two candidates: the maximum node of its left subtree, or the minmum node of its right subtree. Here, the former is used.
Detailed Description
Author
jinya.nosp@m.ng.h.nosp@m.ust@g.nosp@m.mail.nosp@m..com
Function Documentation
static avl_node_t* __avl_add (avl_node_t * root, avl_node_t * root_parent, avl_node_t * node, avl_tree_cmp_fp cmp) static
add a new node into tree root.
Parameters
root the right place in which we add the new node.
root_parent parent of root.
node new node to be added.
cmp compare function.
Returns
avl_node_t
References _avl_node::left, _avl_node::parent, and _avl_node::right.
Referenced by avl_add().
static avl_node_t* __avl_find (avl_node_t * root, avl_node_t * node, avl_tree_cmp_fp cmp) static
genaral binary search tree procedure.
Parameters
root tree root
node
cmp compare function
Returns
found node, or NULL if not found.
References _avl_node::left, and _avl_node::right.
Referenced by avl_find().
void avl_add (avl_tree_t * tree, avl_node_t * node)
add a node to the tree.
Parameters
tree node to be added.
Returns
no
References __avl_add(), _avl_ops::avl_cmp, avl_do_balancing(), avl_is_balanced(), _avl_tree::avl_ops, avl_set_height(), _avl_node::parent, and _avl_tree::root.
void avl_del (avl_tree_t * tree, avl_node_t * node)
delete a node from a tree. When deleting a node, we need to move a new node in the tree to the empty place, there are two candidates: the maximum node of its left subtree, or the minmum node of its right subtree. Here, the former is used.
When deleting a node, we need to move a new node in the tree to the empty place, there are two candidates: the maximum node of its left subtree, or the minmum node of its right subtree. Here, the former is used.
Parameters
tree
node to be deleted.
Returns
none
References avl_do_balancing(), avl_get_max_node(), avl_is_balanced(), avl_set_height(), avl_swap_nodes(), FALSE, _avl_node::left, _avl_node::parent, _avl_node::right, and _avl_tree::root.
bool_t avl_do_balancing (avl_tree_t * tree, avl_node_t * node)
do balancing operation for a tree required. Balance the un-balanced tree at the given node by RR, LL, RL, LR rotation.
Parameters
tree avl tree
node do balancing at the node.
Returns
References _avl_node::left, _avl_node::parent, _avl_node::right, _avl_tree::root, and TRUE.
Referenced by avl_add(), and avl_del().
static avl_node_t* avl_find (avl_tree_t * tree, avl_node_t * node) static
find a node in avl tree.
Parameters
tree avl tree to be searched.
node
Returns
the found node, or NULL if not found.
References __avl_find(), _avl_ops::avl_cmp, _avl_tree::avl_ops, and _avl_tree::root.
int avl_get_balance (avl_node_t * node)
get balance factor of a tree The balance factor of a tree is the height of left subtree minnus height of right subtree. If balance factor is -1, 0, or 1, then it is a balanced tree. If the balance factor at a node is > 0 then the subtree at that node is left heavy. If it is < 0 then it is right heavy.
Parameters
node
Returns
balance factor of a node.
References _avl_node::height, _avl_node::left, and _avl_node::right.
Referenced by avl_is_balanced().
avl_node_t* avl_get_max_node (avl_node_t * node)
get maxmum node in a tree.
Parameters
node
Returns
avl_node_t
References _avl_node::right.
Referenced by avl_del().
avl_node_t* avl_get_min_node (avl_node_t * node)
get mimmum node in a tree.
Parameters
node
Returns
References _avl_node::left.
bool_t avl_is_balanced (avl_node_t * node)
check if a node is banlanced.
Parameters
node.
Returns
TRUE balanced FALSE not balanced
References avl_get_balance(), FALSE, and TRUE.
Referenced by avl_add(), and avl_del().
static void avl_rotate_ll (avl_node_t ** root, avl_node_t * node) static
This performs an LL rotation on the tree at the give node.
This is required when an unblanced node is left-heavy and the subtree to its left is left-heavy too (for example after a node was inserted into the left subtree's left subtree).
An LL rotation goes clockwise - it moves the left sub-node up to the root, and the root node down to the right.
From: N To: L / \ / \ L R A N / \ / \ A* B B R
Where A is the deepest path to the bottom of the tree.
Parameters
root pointer that points to node, i.e. node's parent's child (points to node).
node unbalanced node.
References _avl_node::left, _avl_node::parent, and _avl_node::right.
Referenced by avl_rotate_lr(), and avl_rotate_rl().
static void avl_rotate_lr (avl_node_t ** root, avl_node_t * node) static
This performs an LR rotation on the tree at the give node. This is required when an unblanced node is left-heavy and the subtree to its left is right-heavy (for example after a node was inserted into the left subtree's right subtree).
An LR rotation consists of an RR rotation on the left subtree followed by an LL rotation on the root.
From: N To: N To: B / \ / \ / \ L R B R L N / \ / \ / \ / \ A B L D A C D R / \ / \ C D A C
Parameters
root pointer that points to node, i.e. node's parent's child (points to node).
node unbalanced node.
References avl_rotate_ll(), avl_rotate_rr(), _avl_node::left, and _avl_node::right.
static void avl_rotate_rl (avl_node_t ** root, avl_node_t * node) static
This performs an RL rotation on the tree at the give node. This is required when an unblanced node is right-heavy and the subtree to its right is left-heavy (for example after a node was inserted into the right subtree's left subtree).
An RL rotation consists of an LL rotation on the right subtree followed by an RR rotation on the root.
From: N To: N To: A / \ / \ / \ L R L A N R / \ / \ / \ / \ A B C R L C D B / \ / \ C D D B
Parameters
root pointer that points to node, i.e. node's parent's child (points to node).
node unbalanced node.
References avl_rotate_ll(), avl_rotate_rr(), _avl_node::left, and _avl_node::right.
static void avl_rotate_rr (avl_node_t ** root, avl_node_t * node) static
This performs an RR rotation on the tree at the give node. This is required when an unblanced node is right-heavy and the subtree to its right is right-heavy too (for example after a node was inserted into the right subtree's right subtree).
An RR rotation goes anticlockwise - it moves the right sub-node up to the root, and the root node down to the left.
From: N To: R / \ / \ L R N B / \ / \ A B* L A
Where B is the deepest path to the bottom of the tree.
Parameters
root pointer that points to node, i.e. node's parent's child (points to node).
node unbalanced node.
References _avl_node::left, _avl_node::parent, and _avl_node::right.
Referenced by avl_rotate_lr(), and avl_rotate_rl().
void avl_set_height (avl_node_t * node)
calculate height of all nodes in a tree.
Parameters
node.
Returns
no
References _avl_node::height, _avl_node::left, and _avl_node::right.
Referenced by avl_add(), and avl_del().
void avl_swap_nodes (avl_node_t * node1, avl_node_t * node2, avl_tree_t * tree)
swap positions of node1 and node2. Devide this into 3 cases:
node1 is root;
node2 is root;
Both node1 and node2 are not root.
References FALSE, _avl_node::left, _avl_node::parent, _avl_node::right, and _avl_tree::root.
Referenced by avl_del().